### ISSUE TITLE
Can I specify the sparsity ratio for each layer separately？

### ISSUE THREAD

**Issue by Sugar929** [VainF/Torch-Pruning#102]
I only see an iterative pruning method in the doc.

**Comment by VainF** [comment]
Yes, you can specify fine-grained sparsity using [ch_sparsity_dict](https://github.com/VainF/Torch-Pruning/blob/06c84bacc0feb4f592c98c30f7940a87544cc29b/torch_pruning/pruner/algorithms/metapruner.py#L36). It can be a nested module or just single layer.

For example: ch_sparsity_dict = {model.conv1: 0.43, model.layer1: 0.22}.

**Comment by Sugar929** [comment]
So `ch_sparsity` means setting each layer with the same sparsity ratio=ch_sparsity?  And I can use `ch_sparsity_dict` to set different layers with different sparsity?
Furthermore, if I want to set part of layers with the same sparsity, while others with different values, such as:
conv1:0.1, conv2:0.2, all other layers:0.3.  How can I achieve that without enumeration?

**Comment by VainF** [comment]
Q1: So ch_sparsity means setting each layer with the same sparsity ratio=ch_sparsity?
A1: Yes, ch_sparsity will be applied to all layers that are not in ch_sparsity_dict.

Q2: And I can use ch_sparsity_dict to set different layers with different sparsity?
A2: Yes. ch_sparsity_dict is of a higher priority than ch_sparsity. 

Q3: How can I achieve that without enumeration?
A3: 
```python
MagnitudePruner (..., ch_sparsity = 0.3, ch_sparsity_dict={conv1:0.1, conv2:0.2}, ...)
```

**Comment by Sugar929** [comment]
Thanks for your prompt answer, but error happened when I tried to prune yolox-s  (from [https://github.com/Megvii-BaseDetection/YOLOX](url))

I wanted to prune only one conv layer
Code:
```
imp = tp.importance.MagnitudeImportance(p=2)
pruner = tp.pruner.MagnitudePruner(
      model,
      example_inputs,
      importance=imp,
      iterative_steps=iterative_steps,
      ignored_layers=[],
      ch_sparsity_dict={model.backbone.backbone.dark2[0].conv:0.5}
    )
```
Error:
```
  File "/home/miniconda3/lib/python3.8/site-packages/torch_pruning/pruner/algorithms/metapruner.py", line 98, in __init__
    if isinstance(submodule, prunable_types):
TypeError: isinstance() arg 2 must be a type or tuple of types
```

**Comment by qiulinzhang** [comment]
> Thanks for your prompt answer, but error happened when I tried to prune yolox-s (from [https://github.com/Megvii-BaseDetection/YOLOX](url))
> 
> I wanted to prune only one conv layer Code:
> 
> ```
> imp = tp.importance.MagnitudeImportance(p=2)
> pruner = tp.pruner.MagnitudePruner(
>       model,
>       example_inputs,
>       importance=imp,
>       iterative_steps=iterative_steps,
>       ignored_layers=[],
>       ch_sparsity_dict={model.backbone.backbone.dark2[0].conv:0.5}
>     )
> ```
> 
> Error:
> 
> ```
>   File "/home/miniconda3/lib/python3.8/site-packages/torch_pruning/pruner/algorithms/metapruner.py", line 98, in __init__
>     if isinstance(submodule, prunable_types):
> TypeError: isinstance() arg 2 must be a type or tuple of types
> ```

I met this problem. As TypeError said, "isinstance() arg 2 must be a type or tuple of types", prunable_types is a list, submodule is a type, turning prunable_types list to tuple solves the problems for me.

Modify code line 98 in `/home/miniconda3/lib/python3.8/site-packages/torch_pruning/pruner/algorithms/metapruner.py` 

`if isinstance(submodule, tuple(prunable_types)):`

**Comment by Sugar929** [comment]
@qiulinzhang thank u, it worked. But the pruning process didn't go as I wished...
I took a simpler nerwork to have a try ——vgg16.
```
pruner = tp.pruner.MagnitudePruner(
      model,
      example_inputs,
      importance=imp,
      iterative_steps=iterative_steps,
      ignored_layers=[],
      ch_sparsity_dict={model.features[0]:0.5},
    )
```
I just wanted to prune the first conv layer, but almost the whole network was pruned by 50%.
Or I have to include all unpruned layers in `ignored_layers`? Is there any more elegant method to achieve it?

**Comment by Sugar929** [comment]
@qiulinzhang I read the \_\_init\_\_ code in MetaPruner() and found that `ch_sparsity` was inited by 0.5.
