### ISSUE TITLE
Problems encountered in pruning GAT model

### ISSUE THREAD

**Issue by vegetablelearning** [VainF/Torch-Pruning#104]
In the experiment of the paper, you can prune GAT, but I haven't seen the example of pruning GAT in the code. I want to know how to write the code of this method of pruning GAT, and can this method prune GAT for graph classification?I would be grateful if you could answer my question.

**Comment by VainF** [comment]
Hi @vegetablelearning, We have not released the GAT pruner yet. However, if you are interested, I can provide you with our experimental code through email. Please note that the code is not fully refined and maybe a bit disorganized.

**Comment by vegetablelearning** [comment]
My email is vegetablelearning@163.com.Thank you very much.

**Comment by vegetablelearning** [comment]
I have received your email.  Thank you very much.

**Comment by hojunking** [comment]
Can I get the GAT pruner code too? I really want to know how you apply pruner to graph network. here is my email hojunking@knu.ac.kr 
I would be really thank you if you provide the code. Thank you for your research which is really helpful.

**Comment by mindim01** [comment]
Can I please get the GNN pruner as well? We are using PyG and HeteroDataBatch and we'd love to try out your solution.
My email is mina.dimova@arm.com
Many Thanks!
