### ISSUE TITLE
Is it possible to train the ViT model after it is pruned ?

### ISSUE THREAD

**Issue by johnrachwan123** [VainF/Torch-Pruning#121]
I get the following error after I prune a ViT model using Torch-Pruning:

`RuntimeError: Function AddBackward0 returned an invalid gradient at index 1 - got [65, 128, 1464] but expected shape compatible with [1536]`

This happens when loss.backward() is called so the forward pass runs normally. Have you tested the backward pass after pruning ViT ?

**Comment by VainF** [comment]
Of course, you train a pruned ViT. Did you utilize these [pruners] for ViT pruning?
