### ISSUE TITLE
Using powers for L1, L2 norms calculation in Importance classes

### ISSUE THREAD

**Issue by Serjio42** [VainF/Torch-Pruning#122]
Hello. In [importance.py](https://github.com/VainF/Torch-Pruning/blob/master/torch_pruning/importance.py) there are several `.pow(2)` usages, while there are special parameters `p` / `self.p` for it. For example:
```
class MagnitudeImportance(Importance):
    def __init__(self, p=1, group_reduction="mean", normalizer=None):
        self.p = p
...
...
    local_norm = w.pow(2).sum(1)
```
Looks like it's better to use parameters instead of hard-code "power=2". It could provide using _p=1_ properly for L1 importance calculation, for example. As I correctly understood...

**Comment by VainF** [comment]
I agree with that. I think the importance module should be refactored. It is not very robust to complicated models.

**Comment by Serjio42** [comment]
Just FUI, I've tried to prune for about 600+ models from `timm` library, pruning was successful in ~60% cases.

So, what can we do with this issue: 
- simply throw `p` parameter in importance classes where norms are calculated, for now
or
- wait for refactoring by you team (or you, if you are the only core contributor :) ) ?

**Comment by VainF** [comment]
Bad news: there is only one developer (me) in this project.

> Just FUI, I've tried to prune for about 600+ models from timm library, pruning was successful in ~60% cases.

Oh, really thanks for your effort. I think it is a good idea to establish a benchmark for the applicability of structural pruning. Could you open a new pull request for the timm pruning? I think it would be a valuable work. 

> simply throw p parameter in importance classes where norms are calculated

I have no idea about how to refactor the Importance module so far. Maybe we should just use the p parameter now.

**Comment by Serjio42** [comment]
As I see, the issue case is fixed in the actual code version. Closing the issue.
