### ISSUE TITLE
Meet a bug when pruning ConvTranspose2d

### ISSUE THREAD

**Issue by Siyuluan** [VainF/Torch-Pruning#125]
Hi,

Thanks for your code, I want to use your code in my work, my DNN is 

Class:
self.Linear = nn.Linear(in_features=512, out_features=4096)
self.conv1T1 = nn.ConvTranspose2d(in_channels=256, out_channels=128, kernel_size=4, stride=2, padding=1)
self.conv1T2 = nn.ConvTranspose2d(in_channels=128, out_channels=64, kernel_size=4, stride=2, padding=1)

forward:
x = F.relu(self.Linear(x))
x = x.view(-1,self.conv1T1.in_channels, 4, 4)
x = F.relu(self.conv1T1(x))
x = F.relu(self.conv1T2(x))

And when I use tp.pruner.MagnitudePruner, I met the bug: IndexError: index 2048 is out of bounds for dimension 0 with size 256?

Do you know how to solve it? Do you think this is because self.Linear? When I put self.Linear into the [ignored_layers], then no bug. So do you think it's because of x.view? 

Thanks a lot and have a nice day!

**Comment by VainF** [comment]
Hi @Siyuluan, I think it is caused by the reshaping operation ``x.view`` as it changes the channel numbers. I need to make some modifications to the tp.importance.MagnitudeImportance.

**Comment by Siyuluan** [comment]
Hi @VainF ,

Thank you so much for your reply, looking forward to your modification!

Can you tell me when you modified it? This work is really good and useful, I think this is the most powerful torch pruning tool now! Can't wait to use it! :)  

Have a nice day!

**Comment by VainF** [comment]
I think this is quite important for networks like GANs. So I will update the code ASAP. Maybe tomorrow?

**Comment by Siyuluan** [comment]
@VainF  Super! Hahahah! You are so nice!

**Comment by VainF** [comment]
Hi @Siyuluan,

We have made updates to our code to incorporate reshaping capabilities. However, we are still encountering some issues, as evidenced by the following example, that the pruning ratio of the first 'self.Linear' component does not meet the desired sparsity of 50%. While we have some potential solutions, they would require significant modifications to the core of our code. We are going to resolve this issue in a future version, along with GAN pruning.

## Example:

```python
import torch
import torch.nn as nn
import torch.nn.functional as F

import torch_pruning as tp
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.Linear = nn.Linear(in_features=512, out_features=4096)
        self.conv1T1 = nn.ConvTranspose2d(in_channels=256, out_channels=128, kernel_size=4, stride=2, padding=1)
        self.conv1T2 = nn.ConvTranspose2d(in_channels=128, out_channels=64, kernel_size=4, stride=2, padding=1)
        self.final = nn.Linear(16384, 10)
    def forward(self, x):
        x = F.relu(self.Linear(x))
        x = x.view(-1,self.conv1T1.in_channels, 4, 4)
        x = F.relu(self.conv1T1(x))
        x = F.relu(self.conv1T2(x))
        x = torch.flatten(x, 1)
        x = self.final(x)
        return x

model = Net()
example_inputs = torch.randn(1, 512)
imp = tp.importance.MagnitudeImportance()
ignored_layers = [model.final]

iterative_steps = 5
pruner = tp.pruner.MagnitudePruner(
    model,
    example_inputs,
    importance=imp,
    iterative_steps=iterative_steps,
    ch_sparsity=0.5, # remove 50% channels, ResNet18 = {64, 128, 256, 512} => ResNet18_Half = {32, 64, 128, 256}
    ignored_layers=ignored_layers,
    root_module_types=[nn.ConvTranspose2d, nn.Linear],
)

base_macs, base_nparams = tp.utils.count_ops_and_params(model, example_inputs)
for i in range(iterative_steps):
    pruner.step()
    macs, nparams = tp.utils.count_ops_and_params(model, example_inputs)
    print(model)
    print(
        "  Iter %d/%d, Params: %.2f M => %.2f M"
        % (i+1, iterative_steps, base_nparams / 1e6, nparams / 1e6)
    )
    print(
        "  Iter %d/%d, MACs: %.2f G => %.2f G"
        % (i+1, iterative_steps, base_macs / 1e9, macs / 1e9)
    )
    # finetune your model here
    # finetune(model)
    # ...
```

## Outputs
```
Net(
  (Linear): Linear(in_features=512, out_features=3840, bias=True)
  (conv1T1): ConvTranspose2d(240, 115, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
  (conv1T2): ConvTranspose2d(115, 57, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
  (final): Linear(in_features=14592, out_features=10, bias=True)
)
  Iter 1/5, Params: 2.92 M => 2.66 M
  Iter 1/5, MACs: 0.07 G => 0.06 G
Net(
  (Linear): Linear(in_features=512, out_features=3600, bias=True)
  (conv1T1): ConvTranspose2d(225, 102, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
  (conv1T2): ConvTranspose2d(102, 51, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
  (final): Linear(in_features=13056, out_features=10, bias=True)
)
  Iter 2/5, Params: 2.92 M => 2.43 M
  Iter 2/5, MACs: 0.07 G => 0.05 G
Net(
  (Linear): Linear(in_features=512, out_features=3360, bias=True)
  (conv1T1): ConvTranspose2d(210, 89, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
  (conv1T2): ConvTranspose2d(89, 44, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
  (final): Linear(in_features=11264, out_features=10, bias=True)
)
  Iter 3/5, Params: 2.92 M => 2.20 M
  Iter 3/5, MACs: 0.07 G => 0.04 G
Net(
  (Linear): Linear(in_features=512, out_features=3136, bias=True)
  (conv1T1): ConvTranspose2d(196, 76, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
  (conv1T2): ConvTranspose2d(76, 38, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
  (final): Linear(in_features=9728, out_features=10, bias=True)
)
  Iter 4/5, Params: 2.92 M => 1.99 M
  Iter 4/5, MACs: 0.07 G => 0.03 G
Net(
  (Linear): Linear(in_features=512, out_features=2928, bias=True)
  (conv1T1): ConvTranspose2d(183, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
  (conv1T2): ConvTranspose2d(64, 32, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
  (final): Linear(in_features=8192, out_features=10, bias=True)
)
  Iter 5/5, Params: 2.92 M => 1.80 M
  Iter 5/5, MACs: 0.07 G => 0.02 G
```

**Comment by Siyuluan** [comment]
Hi @VainF,

Thanks for your reply!

1. When I tried to change the DNN structure like you said GAN, and ran the new version of the code, still meet the same bug, "IndexError: index xxx is out of bounds for dimension 0 with size yyy."  

2. Another bug is when I ran the same code multiple times, the number of xxx and yyy will change. 

I guess something about the importance.py ？

But still thanks for your great work, at least I can prune some layers. :)

Btw, do you have a time plan for this BUG? Because if it will take you a long time to solve it, maybe I can prune some layers first. If you think you can solve it in a few days, then I can wait for you.

Thanks again for your super cool tool, hope you can publish a lot of papers in the top journal and conferences!
