### ISSUE TITLE
关于Layer Sparsity

### ISSUE THREAD

**Issue by zhangh0920** [VainF/Torch-Pruning#132]
请问一下，uniform sparsity and learned sparsity是什么意思？是怎么实现的？不是分组进行稀疏的吗，那同组的不同layers又怎么按照不同系数比例来稀疏呢？

**Comment by VainF** [comment]
> uniform sparsity and learned sparsity是什么意思？是怎么实现的？
这个部分和怎么稀疏没有直接关联，他是一个稀疏率/剪枝率怎么分配的问题，只是pruner里的global_pruning是True还是False的区别。如果global_pruning=False，那么所有层使用一样的剪枝率也就是uniform sparsity，如果是global_pruning=True，那么就是整个网络里的参数一起排序，按结果分配稀疏率。

> 同组的不同layers又怎么按照不同系数比例来稀疏呢？
这个问题我可能没有理解，不同layer之间系数是一样的。

**Comment by zhangh0920** [comment]
谢谢你的解答，我明白了。另外还有一个问题想问，这个正则项的作用是什么，在论文中除了提出这个公式之外没有出现第二次
![2023-03-31 11-20-48 的屏幕截图](https://user-images.githubusercontent.com/93476728/229014650-04fb5722-720f-45ca-a453-9e730e820beb.png)
