### ISSUE TITLE
torch 2 support

### ISSUE THREAD

**Issue by lminer** [VainF/Torch-Pruning#138]
Does this work with torch 2.0 and if not, is it planned?

**Comment by VainF** [comment]
Hello @lminer, Torch-Pruning works with Torch2.0.

We use torch 2.0 for testing in the Github Action:

<img width="1291" alt="image" src="https://user-images.githubusercontent.com/18592211/229586394-23ff3bd7-33cd-4af3-9b40-a83ebcbbd909.png">
