### ISSUE TITLE
剪枝后的模型，网络结构已经变化了（即通道数），不适合原来模型结构定义

### ISSUE THREAD

**Issue by eeric** [VainF/Torch-Pruning#139]
对剪枝后的模型，保存模型参数后，再次加载模型参数，没法用原来模型定义。
现在是保存整个模型，包括参数和结构。
请问，能再次加载模型参数吗？

**Comment by VainF** [comment]
您好，如果只保存模型参数，是无法用原始的结构读取参数的，因此需要把整个模型对象存入剪枝后文件。

我们正在开发剪枝历史记录的功能，可以把执行的剪枝记录存储到一个文件，然后从原始定义开始读取并重新执行剪枝。

**Comment by eeric** [comment]
明白，谢谢！

**Comment by VainF** [comment]
新的存储方式已经更新在main branch啦，提供了Pruning History，可以从原始模型定义构建剪枝后的模型。
那么Issue先关闭啦，如果有问题麻烦reopen~

**Comment by eeric** [comment]
good job!
