### ISSUE TITLE
论文求助

### ISSUE THREAD

**Issue by ZS-YANG** [VainF/Torch-Pruning#142]
你好作者，恭喜你发表了如此高水平的文章。我在读论文的时候，看到你引用了这篇文章【1】Alfred V . Aho, Michael R Garey, and Jeffrey D. Ullman. The transitive reduction of a directed graph. SIAM Journal on Computing, 1(2):131–137, 1972. 4，我在网上找了很久都没找到这篇文章的pdf，请问你还有这篇文章的原文PDF嘛？方便共享一下？
感谢表情🤗🤗🤗

**Comment by VainF** [comment]
您好 请参考https://www.cs.tufts.edu/~nr/cs257/archive/al-aho/transitive-reduction.pdf

**Comment by ZS-YANG** [comment]
> 您好 请参考https://www.cs.tufts.edu/~nr/cs257/archive/al-aho/transitive-reduction.pdf

收到，感谢作者😜
