### ISSUE TITLE
'ViewBackward0' object has no attribute '_saved_self_sizes'

### ISSUE THREAD

**Issue by Nidhogn** [VainF/Torch-Pruning#153]
I encountered this problem when I pruned the resnet56 model and defined pruner

**Comment by VainF** [comment]
Hi @Nidhogn, thank you for the issue! we will fix it.

**Comment by VainF** [comment]
Hi @Nidhogn, I noticed that the torch_pruning used in your project is an old version right? Please clone the latest main branch. Thank you.

BTW, torch>=1.12 should work.

**Comment by Nidhogn** [comment]
> Hi @Nidhogn, I noticed that the torch_pruning used in your project was an old version right? Please clone the latest main branch. Thank you.
> 
> BTW, torch>=1.12 should work.

Thanks, it works
