### ISSUE TITLE
prune dla34 backbone

### ISSUE THREAD

**Issue by shuizhilinxin** [VainF/Torch-Pruning#156]
Hello, thank you very much for your work. I am trying to prune the dla34 model, but I have encountered a problem with 
`tensor not matching at non-singleton dimension 0` 
After investigating the reason, I found that there is a convolution `self.project` after a downsample in the tree block of the dla34 model. It seems that the build dependency did not track self.project, which caused the tensor not match issue. 

Can you please tell me how to solve this problem?

**Comment by shuizhilinxin** [comment]
谢谢大佬的回复，这个链接[https://github.com/xingyizhou/CenterNet/blob/2b7692c377c6686fb35e473dac2de6105eed62c6/src/lib/models/networks/dlav0.py](url)

**Comment by janthmueller** [comment]
> 谢谢大佬的回复，这个链接[https://github.com/xingyizhou/CenterNet/blob/2b7692c377c6686fb35e473dac2de6105eed62c6/src/lib/models/networks/dlav0.py](url)，使用def dla34(pretrained, **kwargs): # DLA-34，在Tree block的self.project处failed

Were you able to find and fix the problem? Could you possibly share your results? I'm not too familiar with the Torch-Vision repo, but I have experience with CenterNet and DLA. It seems like the unused layers are a problem: https://github.com/ucbdrive/dla/pull/23#issuecomment-1537982394

**Comment by lebron-2016** [comment]
> 谢谢大佬的回复，这个链接[https://github.com/xingyizhou/CenterNet/blob/2b7692c377c6686fb35e473dac2de6105eed62c6/src/lib/models/networks/dlav0.py](url)，使用def dla34(pretrained, **kwargs): # DLA-34，在Tree block的self.project处failed

您好，请问解决了吗？
