### ISSUE TITLE
哈啰，二维码过期了

### ISSUE THREAD

**Issue by Bobo-y** [VainF/Torch-Pruning#185]
我最近也开始做剪枝，请教作者一下，凭你的经验来说，目前的这些剪枝方法哪个的效果通常好一些呢？我目前在自己的multitask项目中验证了BN-scale ，极限就是剪掉77%，模型缩小到1/13，fp 16 trt 提速度了33%，准备继续验证别的剪枝算法

**Comment by daixiangzi** [comment]
二维码过期+1

**Comment by WenMang98k** [comment]
二维码过期+1
