### ISSUE TITLE
Prune Fast-RCNN error

### ISSUE THREAD

**Issue by hoangdung3498** [VainF/Torch-Pruning#207]
when i prune model Fast-RCNN by:
```
    net = network().to(device)
    net.load_state_dict(torch.load(checkpoint)['state_dict'])
    net.eval()

    for p in net.parameters():
        p.requires_grad_(True)

    iterative_steps = 1 # progressive pruning
    for i in range(iterative_steps):
        step = i
        # Prunings
        example_inputs = torch.randn(1, 3, 832, 1088).to(device)
        #imp = tp.importance.RandomImportance()
        imp = tp.importance.MagnitudeImportance(p=2) # L2 norm pruning

        ignored_layers = []
        #from models.yolo import Detect
        from net.model import RCNN
        for m in net.modules():
            if isinstance(m, RCNN):
                ignored_layers.append(m)
        pruner = tp.pruner.MagnitudePruner(
            net,
            example_inputs,
            importance=imp,
            iterative_steps=iterative_steps,
            ch_sparsity=0.2, # remove 50% channels, ResNet18 = {64, 128, 256, 512} => ResNet18_Half = {32, 64, 128, 256}
            ignored_layers=ignored_layers,
        )
        base_macs, base_nparams = tp.utils.count_ops_and_params(net, example_inputs)
        print("Before Pruning: MACs=%f, #Params=%f"%(base_macs, base_nparams))
        
        pruner.step()
        
        pruned_macs, pruned_nparams = tp.utils.count_ops_and_params(net, example_inputs)
        print("After Pruning: MACs=%f, #Params=%f"%(pruned_macs, pruned_nparams))
        
```
I get error :

> Traceback (most recent call last):
>   File "prune.py", line 370, in <module>
>     eval_all(config, Network)
>   File "prune.py", line 36, in eval_all
>     match_results = inference_bfj(config, network, CHECKPOINT, crowdhuman, start, end)
>   File "prune.py", line 117, in inference_bfj
>     ignored_layers=ignored_layers,
>   File "/DATA/dungha15/envs/vai3.0-pt-v2/lib/python3.7/site-packages/torch_pruning/pruner/algorithms/metapruner.py", line 78, in __init__
>     customized_pruners=customized_pruners,
>   File "/DATA/dungha15/envs/vai3.0-pt-v2/lib/python3.7/site-packages/torch_pruning/dependency.py", line 372, in build_dependency
>     model, example_inputs, forward_fn, output_transform=output_transform
>   File "/DATA/dungha15/envs/vai3.0-pt-v2/lib/python3.7/site-packages/torch_pruning/dependency.py", line 686, in _trace
>     for o in utils.flatten_as_list(out):
>   File "/DATA/dungha15/envs/vai3.0-pt-v2/lib/python3.7/site-packages/torch_pruning/utils/utils.py", line 17, in flatten_as_list
>     flattened_list.extend(flatten_as_list(sub_obj))
> TypeError: 'int' object is not iterable
> python exited with status code 1

Thank for any helps !

**Comment by hoangdung3498** [comment]
@VainF Can torch_pruning helps to prune Fast-RCNN ???

**Comment by nfyfamr** [comment]
Anyone who solved this?
