### ISSUE TITLE
How to prune away an entire layer

### ISSUE THREAD

**Issue by atif-hassan** [VainF/Torch-Pruning#254]
Hi!

Thank you so much for this amazing library!

I am working on my own pruning method which also removes layers and not just the filters/neurons from each layer. How can I implement this using your library?

Please note that I do not need to copy weights from the original model since I am training from scratch so removing layers will not create any issue in my method.

Once again, thank you for this amazing library!!

**Comment by VainF** [comment]
Hi @atif-hassan, removing a layer from the network can be a little complex. A simple solution is to replace your layers with ``nn.Identity``, but this might not work if the layer has different input & output dims.

**Comment by atif-hassan** [comment]
Understood. For now, I have created my own implementation but it would be great if we could have such a feature in the future.

Thank you for the swift response!

**Comment by atif-hassan** [comment]
Understood. For now, I have created my own implementation but it would be great if we could have such a feature in the future.

Thank you for the swift response!

**Comment by VainF** [comment]
> Understood. For now, I have created my own implementation but it would be great if we could have such a feature in the future.
> 
> Thank you for the swift response!

Thank you for the valuable suggestion. We do have a plan in place for layer pruning, but we are still actively searching for a general solution that can be applied across various models.

**Comment by litingsjj** [comment]
> > Understood. For now, I have created my own implementation but it would be great if we could have such a feature in the future.
> > Thank you for the swift response!
> 
> Thank you for the valuable suggestion. We do have a plan in place for layer pruning, but we are still actively searching for a general solution that can be applied across various models.

Great work, have you support this function for now?

**Comment by atif-hassan** [comment]
> Great work, have you support this function for now?

Unfortunately no. As of now, each network needs its own custom pruner which is a lot of manual labour. I am trying to figure out if it is possible to create a general framework that works for any model. Hit me up if you have any ideas!
