### ISSUE TITLE
Does Grouping Strategy in this repo

### ISSUE THREAD

**Issue by HaoLiuHust** [VainF/Torch-Pruning#255]
According to the paper, there are 3 Grouping Strategies, is them in this repo?
![image](https://github.com/VainF/Torch-Pruning/assets/7233091/65bfd18f-0ace-4c6c-a89b-c072de67d312)

**Comment by VainF** [comment]
Yes, the grouping strategy can be controlled with the `group_reduction` and `target_types` in tp.importance

**Comment by HaoLiuHust** [comment]
thanks for your reply, I will try it
