### ISSUE TITLE
Does Torch-Pruning support sharing weight between different pruning structures?

### ISSUE THREAD

**Issue by ChengHan111** [VainF/Torch-Pruning#257]
Hi, first of all, thanks for your great work! I really learn a lot from your paper.
I am wondering if torch-pruning support to optimize a single model with different sparsities, which means the architecture itself are sparsed from a single backbone, while all sparsities share the same weight (for higher sparisity, only partial from the original model is updated accordingly). The question is a little bit tricky. I wish you could give me some hints.

Thank you!

**Comment by VainF** [comment]
Hi @ChengHan111. Could you please share additional information regarding 'different sparsities'? Are you referring to structured and unstructured sparsity? 

Or perhaps you're interested in further sparsifying an already sparse model.

**Comment by ChengHan111** [comment]
Thanks for your reply, I am doing the structural pruning. What I mean different sparsities is that I want to jointly prune a model with different sparsities. Without initiating multiple models, I want to share the weights across different sparsities. Any thoughts? Thank you!

**Comment by ChengHan111** [comment]
Also, I do interested in creating ranking for different sparsity in a single run. For example, by having sparsities ranking from 0.1-0.9, instead of using tp.pruner.MagnitudePruner for several time (I suppose they might be different on different runs? or not, I am not quite sure here), can I use the single run Pruner to generate multiple sparsity maps?

Many thanks.

**Comment by VainF** [comment]
If I understand your question correctly, you are trying to prune different layers with different sparsity. This can be achieved with `ch_sparsity_dict = {model.layer1: 0.3, model.block4: 0.2}`. This allows us to prune blocks/layers with customized sparsity.

**Comment by ChengHan111** [comment]
Hi I guess my question is when I saved some sparsities in state_dict, everytime running load_pruning_history would prune the model once more, resulted in negative convs. Any chance I can load the pruning history solely from the original model I build graph with, without regressively pruning the model? For example, 
```
state_dict = torch.load('pruned_model.pth')
DG = tp.DependencyGraph().build_dependency(model, example_inputs)
for epoch in range(args.num_train_epochs):
      for step, batch in enumerate(train_loader):
            for sparsity in sparsities:
                  sparsity = float(sparsity)
                  DG.load_pruning_history(state_dict[f'pruning[{sparsity}]'])
```

**Comment by ChengHan111** [comment]
Got it. That is exactly what I am asking for! Many thanks!
