### ISSUE TITLE
About normalizer

### ISSUE THREAD

**Issue by winpih** [VainF/Torch-Pruning#259]
I am using your Pruning algorithm in my Detection model based on Vision Transformer. 
Thank you very much.
I have a question about the normalizer.

In v1.2.1, the normalizer of GroupNormImportance used "max" as the default value.
However, in higher versions, the default value was changed to "mean".
Depending on the normalizer, the accuracy of the detection model varies greatly.
What normalizer do the authors of the paper recommend?
In my model, "max" performed better.

Please give me your opinion.
Thank you.

**Comment by VainF** [comment]
Hi @winpih, we used MAX normalizer in our paper. Choosing normalizer is empirical, so please feel free to use a better normalizer.

**Comment by winpih** [comment]
> Hi @winpih, we used MAX normalizer in our paper. Choosing normalizer is empirical, so please feel free to use a better normalizer.

Thank you for your answer.
Have a great day.
