### ISSUE TITLE
PyTorch version

### ISSUE THREAD

**Issue by janthmueller** [VainF/Torch-Pruning#301]
I noticed in your recommendations that you suggest using PyTorch version 1.12.1 and above. I started off with your fantastic package on PyTorch 1.8.0 but eventually shifted to 1.13.1. I employed a MagnitudePruner with MagnitudeImportance for iterative pruning. However, I observed differences in actual pruning outcomes (measured by MACs and params) between these PyTorch versions. Is this recommendation based on specific package development or certain features? I took precautions like setting seeds and enforcing deterministic algorithms to rule out non-determinism as a cause, but the issue persisted. Any insights into why this discrepancy might occur?

**Comment by VainF** [comment]
Hi @janthmueller, thanks for reaching out. Network tracing can be easier with newer PyTorch but this will not affect the pruning behaviour. Will check it soon.

**Comment by janthmueller** [comment]
I've identified the issue—I overlooked implementing additional integrity tests for my GPU models. Inconsistencies arose in a custom layer using different CUDA versions. Given that it's unrelated to your repository, I'll be closing this issue.
