### ISSUE TITLE
Error when pruning keeps only a single filter

### ISSUE THREAD

**Issue by Roulbac** [VainF/Torch-Pruning#36]
Error
```
   File "/home/reda/miniconda3/envs/yolov5/lib/python3.8/site-packages/torch_pruning/dependency.py", line 375, in get_pruning_plan
    _fix_denpendency_graph(root_node, pruning_fn, idxs)
  File "/home/reda/miniconda3/envs/yolov5/lib/python3.8/site-packages/torch_pruning/dependency.py", line 368, in _fix_denpendency_graph
    if len(new_indices)==0:
TypeError: object of type 'int' has no len()
```
What the node looks like
```
<Node: (6.m.0.cv2.conv (Conv2d(128, 2, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)), <MkldnnConvolutionBackward object at 0x7f05ceabb2e0>)>
```
What this looks like is that pruning this layer outputs a single-channel Conv2D, and then new_indices takes the value of single int rather than a list.

**Comment by Roulbac** [comment]
@VainF Any pointers? I might be able to help fix this

**Comment by VainF** [comment]
Hi @Roulbac , sorry for the late reply (a little busy last month).

It would be great if you can help fix this bug. Please open a new pull request.

**Comment by Roulbac** [comment]
Seems the issue was fixed by

https://github.com/VainF/Torch-Pruning/commit/b2ea30bebebe8102a3fd50a4d5a5e7bbe933ea1e#diff-51b7b62d6ddc1055af03f97ee70345ef60e99fe72579cd6ad48f3a1f86b4befe
