### ISSUE TITLE
detecting unwrapped parameters

### ISSUE THREAD

**Issue by NicholasKiefer** [VainF/Torch-Pruning#364]
When specifying unwrapped parameters, the function `_detect_unwrapped_parameters(...)` always fails, in line  664 in torch_pruning.dependency [here](https://github.com/VainF/Torch-Pruning/blob/master/torch_pruning/dependency.py#L641):
```
        unwrapped_detected = list( set(unwrapped_detected) - set([p for (p, _) in unwrapped_parameters]) )
```
because python will fail on `[p for (p, _) in unwrapped_parameters]`, because `unwrapped_parameters` is a dict. I don't know enough about the code to do a pull request fixing that.

**Comment by janthmueller** [comment]
It seems the typing hint provided is incorrect. Based on my understanding and examples provided in the documentation, it should be `typing.List[typing.Tuple[nn.Parameter, int]]`. This can be confirmed by referring to the [Wiki for High-level Pruners](https://github.com/VainF/Torch-Pruning/wiki/4.-High%E2%80%90level-Pruners), specifically looking into the `unwrapped_parameters` section.
