### ISSUE TITLE
Isomorphic pruning integration into Torch-pruning

### ISSUE THREAD

**Issue by Hrayo712** [VainF/Torch-Pruning#400]
Hi @VainF ,

Thanks for the amazing work!

I was wondering if its in the roadmap to integrate the Isomorphic pruner into the upstream Torch-Pruning framework, and if there would be an ETA for this :)

Thanks!

**Comment by VainF** [comment]
Hi @Hrayo712, thanks for the issue. We will integrate the isomorphism trick into TP. It will be ready in the following one or two weeks.

**Comment by VainF** [comment]
Integrated into v1.4.1. Thanks!

Isomorphic pruning can be enabled by setting ``isomorphic=True`` in any ``tp.pruner``.
