### ISSUE TITLE
deformable convolution

### ISSUE THREAD

**Issue by AvrahamRaviv** [VainF/Torch-Pruning#413]
Hi
Does your code support deformable convolution (deform_conv2d)?
Thanks

**Comment by janthmueller** [comment]
It doesn't provide one out of the box, but you can define an appropriate one for it as in [function.py](https://github.com/VainF/Torch-Pruning/blob/master/torch_pruning/pruner/function.py) or as explained in the wiki for [customized layers](https://github.com/VainF/Torch-Pruning/blob/master/tests/test_customized_layer.py).

**Comment by AvrahamRaviv** [comment]
Thanks!
