### ISSUE TITLE
Bug with rounding

### ISSUE THREAD

**Issue by Serjio42** [VainF/Torch-Pruning#42]
HI, @VainF . I've found a bug it the rounding function `round_pruning_amount` from `strategy.py`.
The case is with parameters: total_parameters=30, n_to_prune=1, round_to=8 . Current function code returns "-2" that raises an error. The right return variant is "6".
My suggestion is to add extra condition the 14'th line in `strategy.py`:
`    if (compensation < round_to // 2 or n_to_prune + compensation < round_to) and after_pruning > round_to:`

**Comment by VainF** [comment]
Thanks! a condition was added in that line to avoid negative rounding.
