### ISSUE TITLE
PixelShuffle

### ISSUE THREAD

**Issue by AvrahamRaviv** [VainF/Torch-Pruning#420]
Hi,
torch.nn.PixelShuffle is change the number of channels, which is not treated well using torch pruning.
For example, I have layer with shape of 1*16*576*1024, and by using PixelShuffle the output is 1*4*1152*2048.
Using torch pruning, dep graph think it is layer with same output channels, which cause to two errors:
1. Number of PixelShuffle's output channels should be reduced/increased by the relevant factor.
2. Number of next layer's input channels should be reduced/increased by the relevant factor as well.
How can I handling it?
Thanks!

**Comment by angelinimattia** [comment]
I Implemented it for my thesis. Usually Intrinsically the PixelShuffle is never pruned, it only expect an input depth as such I bundled the PixelShuffle operator together with the sub-pixel convolution usually putted before it for the SR operation. At this point the operation becomes the following: which are the output channel to prune in the conv layer given an input channel.
You can find my implementation here where the Upsample block represent the standard Upsample operation Conv2D(n, n*(s^2)), where s is the scaling factor and the pixelshuffle layer following it.

https://github.com/MaGiiK02/sr_structured_pruning/blob/main/pruners/UpsamplePruner.py

**Comment by AvrahamRaviv** [comment]
@angelinimattia 
Wow, thanks for the reply! It’s great to see others have tackled this implementation. I’ll be sure to integrate it into my code soon.

**Comment by AvrahamRaviv** [comment]
@angelinimattia
I will! thanks
