### ISSUE TITLE
Rounding bug

### ISSUE THREAD

**Issue by Serjio42** [VainF/Torch-Pruning#49]
HI, @VainF . There is one more bug, has found in _Torch-Pruning/torch_pruning/prune/strategy.py_ in `def round_pruning_amount` .
The thing is when you meet that cases:
```
round_pruning_amount(total_parameters=16, n_to_prune=1, round_to=16)
>> 16
```
And after that pruning behavior, layer left without all parameters, that is an error. The right pruning behavior is to return pruning amount = 0.
So, I propose add correction line in `def round_pruning_amount` after 11'th line in _Torch-Pruning/torch_pruning/prune/strategy.py_:
```elif total_parameters <= round_to: return 0```

We also can change the entire rounding function to more clear but rougher rounding logic:
```
def round_pruning_amount(total_parameters, n_to_prune, round_to):
    """round the parameter amount after pruning to an integer multiple of `round_to`.
    """
    n_remain = round_to*max(int(total_parameters - n_to_prune)//round_to, 1)
    return max(total_parameters - n_remain, 0)
```

Both the variants will correct existing bug. What you think?

**Comment by VainF** [comment]
Thanks! I prefer the second version as it looks more elegant.
