### ISSUE TITLE
Module 'torch_pruning' has no attribute 'importance'

### ISSUE THREAD

**Issue by LeroyGitBash** [VainF/Torch-Pruning#79]
Hello, 
im try to run the example code given in the GIT repo. 

I installed the "torch_pruning" pkg via pip installer.  
My current version of torch_pruning pkg is 0.2.8 

When im running the comand line
"imp = tp.importance.MagnitudeImportance(p=2) # L2 norm pruning" 
from the oficial GIT repo
i am geting the error Module 'torch_pruning' has no attribute 'importance'

I imported the following pkg
import torch
import torchvision
import torch.nn.utils.prune
import torch_pruning as tp

**Comment by VainF** [comment]
Hi @LeroyGitBash, thanks for your feedback! The pip package has not been updated yet. You can clone the repo to get the lastest version.

**Comment by LeroyGitBash** [comment]
Great, thank's now its working

**Comment by satabios** [comment]
@LeroyGitBash Can you explain how did you install the latest version?
