### ISSUE TITLE
test_graph_drawing.py not working

### ISSUE THREAD

**Issue by novothsz** [VainF/Torch-Pruning#83]
Hi!
I just wanted to try out the test_graph_drawing.py script, but it errored-out, because DG.PRUNING_FN is not defined anymore. Would you mind updating this part of the code? Visualisations are always great to have!

**Comment by VainF** [comment]
Hi @novothsz, I fixed this problem in branch v1.0. Thank you for raising the issue!

**Comment by novothsz** [comment]
It works now, thank you for the quick fix!
