### ISSUE TITLE
Small bug? metapruner.py line:96

### ISSUE THREAD

**Issue by novothsz** [VainF/Torch-Pruning#85]
Sorry, isn't [this](https://github.com/VainF/Torch-Pruning/blob/70a2a7fb92bb09cd4594b229ca9bbedd1e21d288/torch_pruning/pruner/algorithms/metapruner.py#L96) line supposed to be:
`for submodule in module.modules():`

**Comment by VainF** [comment]
Fixed! Thank you very much!

**Comment by novothsz** [comment]
Great, thank you!
