### ISSUE TITLE
V1.0 developing status

### ISSUE THREAD

**Issue by HuangVictorAuto** [VainF/Torch-Pruning#90]
Thanks for your great work! I have some question about the developing stage of the v1.0.

Is the BNScalePruner and the corresponding BNScaleImportance finished in the developing branch v1.0?
Is there any tutorial on how to use the BNScalePruner?
Is the listed features in ReadMe already implemented?
![image](https://user-images.githubusercontent.com/54128861/209963803-d915493e-122d-4314-b114-037253e2bccc.png)

**Comment by HuangVictorAuto** [comment]
@VainF , Fang. I saw you still updating the 1.0 branch. I really want to use your pruning tool on my project. Could you tell us the developing extend of the 1.0 branch, what functions are ready, what is still in developoing?

**Comment by VainF** [comment]
Hi @HuangVictorAuto, I'm trying to fix some issues so that it can be merged into the main branch. BNScalePruner is ready now.

Besides, I will upload some quantitative results for CIFAR-10/ResNet-56 today.

**Comment by HuangVictorAuto** [comment]
> Hi @HuangVictorAuto, I'm trying to fix some issues so that it can be merged into the main branch. All features, including BNScalePruner, are ready now.
> 
> Besides, I will upload some quantitative results for CIFAR-10/ResNet-56 today.
